### ISSUE TITLE
WSSE problem with Symfony3

### ISSUE THREAD

**Issue by MarcSky** [djoos/EscapeWSSEAuthenticationBundle#81]
I find problem with file services.yml and make hot fix
prev version file:
services:
    escape_wsse_authentication.provider:
        class:  %escape_wsse_authentication.provider.class%
        arguments: [@security.user_checker, null, null, null, null, 300, '/^([\+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))([T\s]((([01]\d|2[0-3])((:?)[0-5]\d)?|24\:?00)([\.,]\d+(?!:))?)?(\17[0-5]\d([\.,]\d+)?)?([zZ]|([\+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/']
new version
services:
    escape_wsse_authentication.provider:
        class:  %escape_wsse_authentication.provider.class%
        arguments: ['@security.user_checker', null, null, null, null, 300, '/^([\+-]?\d{4}(?!\d{2}\b))((-?)((0[1-9]|1[0-2])(\3([12]\d|0[1-9]|3[01]))?|W([0-4]\d|5[0-2])(-?[1-7])?|(00[1-9]|0[1-9]\d|[12]\d{2}|3([0-5]\d|6[1-6])))([T\s]((([01]\d|2[0-3])((:?)[0-5]\d)?|24\:?00)([\.,]\d+(?!:))?)?(\17[0-5]\d([\.,]\d+)?)?([zZ]|([\+-])([01]\d|2[0-3]):?([0-5]\d)?)?)?)?$/']

i change  - arguments: ['@security.user_checker'
please make hot commit and fix this

**Comment by xub** [comment]
yes please add '' in '@security.user_checker'  Symfony3
